### ISSUE TITLE
two "+"s in a row in string concat

### ISSUE THREAD

**Issue by zenfish** [Miserlou/chords2midi#13]
Line 124 in c2m.py dies (triggered by an existing file; it tries to add a timestamp) -

filename = self.vargs['key'] + '-' + '-'.join(progression) + '-' + str(self.vargs['bpm']) +  + '-' + str(int(time.time())) + '.mid'

subbing one plus for two ('+ +' -> '+') seems to work.

**Comment by Miserlou** [comment]
Should be fixed for a while now

**Comment by Miserlou** [comment]
Thanks for reporting
